parameters:
    ovJsonRpcApiSwaggerPath: '%env(string:OV_JSON_RPC_API_SWAGGER_PATH)%'
    accessControlAllowOriginList: '%ov_json_rpc_api.access_control_allow_origin_list%'

services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true
        bind:
            $accessControlAllowOriginList: '%accessControlAllowOriginList%'

    OV\JsonRPCAPIBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/OVJsonRPCAPIBundle.php'

    _instanceof:
        OV\JsonRPCAPIBundle\Core\ApiMethodInterface:
            tags: ['ov.rpc.method']

    ov_json_rpc_api_index_controller:
        class: OV\JsonRPCAPIBundle\Controller\ApiController
        autoconfigure: true
        public: true
        tags:
            - 'controller.service_arguments'

    Symfony\Component\DependencyInjection\Container: '@service_container'

    ov_json_rpc_api_swagger_generate_command:
        class: OV\JsonRPCAPIBundle\Command\SwaggerGenerate
        autoconfigure: true
        public: true
        arguments:
            $ovJsonRpcApiSwaggerPath: '%ovJsonRpcApiSwaggerPath%'
            $swagger: '%ov_json_rpc_api.swagger%'
        tags:
            - { name: console.command, command: 'ov:swagger:generate' }

    OV\JsonRPCAPIBundle\Command\SwaggerGenerate: '@ov_json_rpc_api_swagger_generate_command'